- name: patching server
  hosts: 
  become: yes
  tasks:
    - name: installing packages
      apt-get:
          name: httpd
          state: present
    - name: starting service
      service:
          name: httpd
          state: started
          enabled: yes
