- name: patching server
  hosts: 172.17.0.2 
  become: yes
  tasks:
    - name: installing packages
      apt:
        name: httpd
        state: present
    - name: starting service
      service:
          name: httpd
          state: started
          enabled: yes
