- name: patching server
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: installing packages
      apt:
        name: apache2
        state: present
    - name: starting service
      service:
          name: apache2
          state: started
          enabled: yes

